name: Build Ghostty Binary

on:
  workflow_call:
    inputs:
      build_matrix:
        description: 'Build matrix as JSON string'
        required: true
        type: string
      zig_version:
        description: 'Zig version to use'
        required: false
        type: string
        default: "0.15.2"
      version_type:
        description: 'Version type to build: "tip" or "release"'
        required: false
        type: string
        default: "tip"

jobs:
  build-ghostty:
    name: Ghostty Binary
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(inputs.build_matrix) }}
    runs-on: ${{ matrix.runner }}
    steps:
        # See the docs: https://github.com/docker/build-push-action
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # This action checks out the source as part of the action and can therefore
        # go before the checkout step.
      - name: Build Docker Image
        uses: docker/build-push-action@v6
        with:
          tags: ghostty:${{ matrix.builds.distro }}-${{ matrix.builds.version }}-${{ matrix.arch }}-${{ inputs.zig_version }}
          context: "{{defaultContext}}:build-binary"
          build-args: |
            DISTRO=${{ matrix.builds.distro }}
            DISTRO_VERSION=${{ matrix.builds.version }}
            ZIG_VERSION=${{ inputs.zig_version }}
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout ghostty-ubuntu
        uses: actions/checkout@v4

      - name: Build Ghostty
        run: |
          docker run --rm -v$PWD/build-binary:/workspace -w /workspace ghostty:${{ matrix.builds.distro }}-${{ matrix.builds.version }}-${{ matrix.arch }}-${{ inputs.zig_version }} /bin/bash build-ghostty.sh ${{ inputs.version_type }}
          mv ./build-binary/ghostty_*.deb ./

      - name: Lint .deb Package
        # Lintian shouldn't fail our build yet
        run: docker run --rm -v$PWD:/workspace -w /workspace ghostty:${{ matrix.builds.distro }}-${{ matrix.builds.version }}-${{ matrix.arch }}-${{ inputs.zig_version }} lintian ghostty_*.deb || true

      - name: Test Installation
        run: docker run --rm -v$PWD:/workspace -w /workspace ghostty:${{ matrix.builds.distro }}-${{ matrix.builds.version }}-${{ matrix.arch }}-${{ inputs.zig_version }} dpkg -i ghostty_*.deb

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ matrix.builds.distro }}-${{ matrix.builds.version }}-${{ matrix.arch }}-${{ inputs.zig_version }}
          retention-days: 7
          path: ghostty_*.deb
